apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: homelab-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: nginx
          image: ghcr.io/hxong/acer-lab-sample-app:25d8f79
          ports:
            - containerPort: 80
