apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-web-2
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-web-2
    app.kubernetes.io/part-of: acer-lab
spec:
  project: default

  source:
    repoURL: https://github.com/hxong/acer-lab-gitops.git
    targetRevision: main
    path: charts/basic-web-app
    helm:
      valueFiles:
        - ../../apps/demo-web-2/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-web-2

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
