apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-web
  namespace: argocd
  labels:
    app.kubernetes.io/name: demo-web
    app.kubernetes.io/part-of: acer-lab
    acer-lab.io/owner: hongxun
    acer-lab.io/team: homelab
spec:
  project: default

  source:
    repoURL: https://github.com/hxong/acer-lab-gitops.git
    targetRevision: main
    path: charts/basic-web-app
    helm:
      valueFiles:
        - ../../apps/demo-web/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-web

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
